name: discord
version: 0.0.2
summary: Free voice and text chat
description: |
 All-in-one voice and text chat for gamers that's free, secure, and
 works on both your desktop and phone. Stop paying for TeamSpeak
 servers and hassling with Skype. Simplify your life.

grade: stable
confinement: strict

parts:
  discord:
    plugin: dump
    source: https://dl.discordapp.net/apps/linux/0.0.2/discord-0.0.2.deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=discord|Icon=/usr/share/discord/discord\.png|' usr/share/discord/discord.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - gconf2
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  discord:
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    command: env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/usr/share/discord/Discord
    desktop: usr/share/applications/discord.desktop
    plugs:
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - x11
      - opengl
      - bluez
